const fs=require('fs');
const path=require('path');
const root=__dirname;
const output=path.join(root,'dist');
fs.mkdirSync(path.join(output,'server'),{recursive:true});
fs.mkdirSync(path.join(output,'.openai'),{recursive:true});
fs.mkdirSync(path.join(output,'client'),{recursive:true});
for(const name of ['index.html','style.css','app.js','ai-lace-study.png','luzzu-maltese-lace-render.png','future-heritage-lab-logo-white.png'])fs.copyFileSync(path.join(output,name),path.join(output,'client',name));
fs.copyFileSync(path.join(root,'worker','index.js'),path.join(output,'server','index.js'));
fs.copyFileSync(path.join(root,'worker','bobbin-brief.js'),path.join(output,'server','bobbin-brief.js'));
fs.copyFileSync(path.join(output,'bobbin-ui.js'),path.join(output,'client','bobbin-ui.js'));
for(const name of ['fabrication.js','fabrication-mesh.js','fabrication-view.js','fabrication-smooth.js','fabrication-worker.js','fabrication-lines.js'])fs.copyFileSync(path.join(output,name),path.join(output,'client',name));
fs.copyFileSync(path.join(root,'.openai','hosting.json'),path.join(output,'.openai','hosting.json'));
console.log('Sites build ready: static assets and Worker entrypoint');
