const http=require('http'),fs=require('fs'),path=require('path');
try{const env=fs.readFileSync(path.join(__dirname,'.env'),'utf8');for(const line of env.split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);if(m&&m[2]&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'')}}catch{}
const root=path.join(__dirname,'dist');const port=Number(process.env.PORT||4173);let busy=false;
const allow={motif:['rosette','scroll','botanical','diamond'],repeat:['halfdrop','grid','mirror','radial','organic'],ground:['diamond','hexagonal','bridges','none'],detail:['balanced','simple','intricate'],edge:['repeat','scallop','pointed','straight'],surface:['ink','thread','cutwork'],quality:['low','medium','high']};
function json(res,status,obj){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'http://127.0.0.1:'+port});res.end(JSON.stringify(obj))}
function readBody(req){return new Promise((resolve,reject)=>{let s='',n=0;req.on('data',c=>{n+=c.length;if(n>10000)reject(new Error('Request too large'));else s+=c});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
function buildPrompt(s){return `Create one square, flat lace pattern study for material research. Motif: ${s.motif}; arrangement: ${s.repeat}; ground: ${s.ground}; open space: ${s.density} percent; thread weight ${s.weight} of 5; detail ${s.detail}; edge ${s.edge}; surface ${s.surface}. Orthographic, edge-to-edge, no perspective, shadows, garments, boats, lettering or watermark. Keep the pattern visually connected with a legible motif and smaller ground. Exploratory specimen, not a certified seamless repeat or engineering drawing.`}
async function generate(req,res){if(busy)return json(res,429,{error:'A generation is already running. Please wait for it to finish.'});if(!process.env.OPENAI_API_KEY)return json(res,503,{error:'OpenAI API key is not configured on the server.'});let body;try{body=await readBody(req)}catch(e){return json(res,400,{error:e.message})}const s=body.settings||{};for(const [k,values] of Object.entries(allow))if(!values.includes(s[k]))return json(res,400,{error:`Invalid pattern option: ${k}`});if(!Number.isInteger(s.density)||s.density<20||s.density>80||!Number.isInteger(s.weight)||s.weight<1||s.weight>5)return json(res,400,{error:'Invalid numeric setting'});busy=true;const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),120000);try{const api=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_IMAGE_MODEL||'gpt-image-2',prompt:buildPrompt(s),size:'1024x1024',quality:s.quality,n:1,output_format:'png'}),signal:ctrl.signal});const data=await api.json();if(!api.ok)return json(res,api.status,{error:data?.error?.message||'OpenAI image generation failed.'});const image=data?.data?.[0]?.b64_json;if(!image)return json(res,502,{error:'OpenAI returned no image data.'});return json(res,200,{image,model:process.env.OPENAI_IMAGE_MODEL||'gpt-image-2',settings:s})}catch(e){return json(res,e.name==='AbortError'?504:502,{error:e.name==='AbortError'?'The image request timed out.':`Image service unavailable: ${e.message}`})}finally{clearTimeout(timer);busy=false}}
function serve(req,res){let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname)}catch{return res.writeHead(400).end()}const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,data)=>{if(e)return res.writeHead(404).end('Not found');const ext=path.extname(file).slice(1),types={html:'text/html; charset=utf-8',css:'text/css',js:'text/javascript',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',svg:'image/svg+xml'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream'});res.end(data)})}
http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'http://127.0.0.1:'+port,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});return res.end()}if(req.url==='/api/health')return json(res,200,{configured:Boolean(process.env.OPENAI_API_KEY),model:process.env.OPENAI_IMAGE_MODEL||'gpt-image-2'});if(req.url==='/api/generate'&&req.method==='POST')return generate(req,res);serve(req,res)}).listen(port,'127.0.0.1',()=>console.log(`Lace Lab: http://127.0.0.1:${port}`));
